### ISSUE TITLE
NPE at corgiaoc.byg.client.textures.ColorManager.onItemColorsInit

### ISSUE THREAD

**Issue by aaronhowser1** [AOCAWOL/BYG-1#34]
__**API/Modloader**__
Forge

Crash when launching with `byg-1.3.4`

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - https://paste.ee/p/TpWYH
Debug.log - [debug.log](https://github.com/AOCAWOL/BYG-1/files/7150247/debug.log)
Latest.log - https://paste.ee/p/qyZ8s

**Comment by aaronhowser1** [comment]
This was apparently caused by another mod, sorry!

**Comment by CorgiTaco** [comment]
> This was apparently caused by another mod, sorry!

Which mod? Several users have been reporting this issue aswell

**Comment by aaronhowser1** [comment]
I fixed it by downgrading all FTB mods to what I had before:
![image](https://user-images.githubusercontent.com/15698722/133002771-356b52b7-dcd1-4a13-826b-f5204b06b867.png)

**Comment by CorgiTaco** [comment]
> I fixed it by downgrading all FTB mods to what I had before:
> ![image](https://user-images.githubusercontent.com/15698722/133002771-356b52b7-dcd1-4a13-826b-f5204b06b867.png)
> 
> I'm not sure which specifically is at fault, but I've forwarded it to the devs

I'd you find out who, please mention this issue on their tracker/the name of the mod!

**Comment by BrisingrAerowing** [comment]
I'm getting this, and disabling the FTB mods I have didn't work. Looking through the code, it seems that the itemColors passed into the handler is null for whatever reason (as that seems to be the only thing on that line that could be null). The null check right before actually checks a delegate created right above, and that should never be null.

**Comment by BrisingrAerowing** [comment]
```text
java.lang.NoClassDefFoundError: dev/ftb/mods/ftblibrary/net/snm/SimpleNetworkManager
	at dev.ftb.mods.ftbbanners.net.FTBBannersNet.<clinit>(FTBBannersNet.java:8) ~[ftbbanners:1605.1.3-build.25]
	at dev.ftb.mods.ftbbanners.FTBBanners.<init>(FTBBanners.java:66) ~[ftbbanners:1605.1.3-build.25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: dev.ftb.mods.ftblibrary.net.snm.SimpleNetworkManager
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 15 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
		at dev.ftb.mods.ftbbanners.net.FTBBannersNet.<clinit>(FTBBannersNet.java:8) ~[ftbbanners:1605.1.3-build.25]
		at dev.ftb.mods.ftbbanners.FTBBanners.<init>(FTBBanners.java:66) ~[ftbbanners:1605.1.3-build.25]
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_212]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) [?:1.8.0_212]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
```

Here's the root error that breaks further loading. You had the wrong version of FTB Library. It appears that if a ClassNotFoundException is thrown due to a mod failing to properly require dependencies, loading will halt later with the error at the end of the log. I had this same issue with another mod not properly listing dependencies.

**Comment by Sintinium** [comment]
I keep getting this issue as well. There's no one mod that causes it from what I find. So far "Game Menu Remove GFARB" and "Yung's better dungeons" have both cause it for me

**Comment by aaronhowser1** [comment]
Reopening since this apparently is a BYG-caused problem. FTB dev says it's something to do with using mixins for colors?

**Comment by CorgiTaco** [comment]
not sure how. I dont get the issue on my end

**Comment by BrisingrAerowing** [comment]
From what I understand, a crash early in the loading process won’t halt the game until much later, with misleading errors. Mods not properly defining dependencies seems to be a major cause of such crashes.

**Comment by CorgiTaco** [comment]
@BrisingrAerowing this is, other people have mentioned this same error

**Comment by CorgiTaco** [comment]
I am under the assumption this is a race condition as it doesnt occur all the time
